In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
import lightgbm as lgb
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
#Read data from csv
train = pd.read_csv('../input/detecting-accounting-errors/Restate_int_train.csv')
test = pd.read_csv('../input/detecting-accounting-errors/Restate_int_test.csv')
external = pd.read_csv('../input/smu-forcasting/WRDS.csv') #external data
data_dict = pd.read_excel('../input/smu-forcasting/DataDictionary_v2.xlsx') #list of features that we are going to use

In [3]:
data_dict.head()

   Formula          ...                        Account
0    gvkey          ...                            NaN
1    fyear          ...                            NaN
2  acominc          ...           Comprehensive Income
3     aedi          ...               Accrued Expenses
4      act          ...                         Assets

[5 rows x 3 columns]

# 1. Exploratory Data Analysis

## 1.1 Find percentage of missing data

In [4]:
data_dict.head()

   Formula          ...                        Account
0    gvkey          ...                            NaN
1    fyear          ...                            NaN
2  acominc          ...           Comprehensive Income
3     aedi          ...               Accrued Expenses
4      act          ...                         Assets

[5 rows x 3 columns]

In [5]:
external.head()

   GVKEY  datadate  fyear     ...       sic spcsrc     ipodate
0   1004  20050531   2004     ...      5080      B  19880101.0
1   1004  20060531   2005     ...      5080      B  19880101.0
2   1004  20070531   2006     ...      5080      B  19880101.0
3   1004  20080531   2007     ...      5080      B  19880101.0
4   1004  20090531   2008     ...      5080      B  19880101.0

[5 rows x 98 columns]

In [6]:
#Now we only take the list of features from the DataDictionary_v2.xlsx
feature_list = data_dict['Formula'].values.tolist() #create a list of features
external.rename(columns={'GVKEY': 'gvkey'}, inplace=True)
external = external[feature_list] #filter out
external.rename(columns={'fyear': 'year'}, inplace=True)

#change column name into gvkey and year

In [7]:

def find_missing(data):
    cnt_missing = data.isnull().sum().values #number of missing values
    total = data.shape[0] # total records
    ratio_missing = cnt_missing/total*100 #percentage of missing
    
    return pd.DataFrame(data ={'missing_count': cnt_missing, 'missing_ratio_percentage' : ratio_missing}, index = data.columns.values)
df_missing = find_missing(external)
df_missing.style.set_properties(**{'text-align': 'left'})
# df_missing.sort_values(['missing_count','missing_ratio_percentage'],ascending = False)

In [8]:
#We only take 
df_missing.reset_index(drop= False,inplace = True)
ext_feature = df_missing[df_missing['missing_ratio_percentage']<15]['index'].values #take feature with less than 15% missing values

In [9]:
#then we are using these feature to merge with our train and test data 
external = external[ext_feature] #filter out these feature
external = external.select_dtypes(exclude=['object']) #for now we dont take categorical features 
train = train.merge(right = external,on =['gvkey','year'],how= 'left')
test = test.merge(right = external,on =['gvkey','year'],how= 'left')

In [10]:
train.shape

(15213, 45)

In [11]:
#convert to date time
train['Date'] =  pd.to_datetime(train['Date'])
test['Date'] =  pd.to_datetime(test['Date'])

train.head()

   gvkey  year                Filing   ...     au  auop  auopic
0   1004  2005  0001104659-05-033688   ...    6.0   1.0     1.0
1   1004  2006  0001104659-06-047248   ...    6.0   1.0     1.0
2   1004  2007  0001104659-07-055173   ...    6.0   1.0     1.0
3   1004  2008  0001047469-08-008126   ...    6.0   1.0     1.0
4   1004  2009  0001047469-09-006783   ...    6.0   4.0     1.0

[5 rows x 45 columns]

In [12]:
train['Restate_Int'].value_counts()

0    14850
1      363
Name: Restate_Int, dtype: int64

In [13]:
#sort by gvkey and year
train.sort_values(['gvkey','year'],inplace = True)
test.sort_values(['gvkey','year'],inplace = True)

In [14]:
train['year'].value_counts()

2005    3112
2009    3111
2006    3017
2008    2998
2007    2975
Name: year, dtype: int64

# 2.Feature engineering

In [15]:
train['Weekday'] = train['Date'].dt.dayofweek
test['Weekday'] = test['Date'].dt.dayofweek
test.head()

   gvkey  year                Filing   ...    auop  auopic  Weekday
0   1004  2010  0001047469-10-006500   ...     NaN     NaN        4
1   1045  2010  0000006201-10-000006   ...     1.0     1.0        2
2   1050  2010  0001193125-10-069639   ...     1.0     0.0        0
3   1072  2010  0000859163-10-000020   ...     NaN     NaN        3
4   1075  2010  0000950123-10-014366   ...     4.0     1.0        4

[5 rows x 45 columns]

In [16]:
train['Date_lag'] = train.groupby('gvkey')['Date'].shift(1)
test['Date_lag'] = test.groupby('gvkey')['Date'].shift(1)
train['Date_diff'] = (train['Date'] -train['Date_lag']).dt.days -365
test['Date_diff'] = (test['Date'] -test['Date_lag']).dt.days - 365

In [17]:
train.head()

   gvkey  year                Filing    ...     Weekday   Date_lag  Date_diff
0   1004  2005  0001104659-05-033688    ...           4        NaT        NaN
1   1004  2006  0001104659-06-047248    ...           0 2005-07-22       -5.0
2   1004  2007  0001104659-07-055173    ...           4 2006-07-17        3.0
3   1004  2008  0001047469-08-008126    ...           4 2007-07-20       -8.0
4   1004  2009  0001047469-09-006783    ...           3 2008-07-11        5.0

[5 rows x 48 columns]

In [18]:
train['Week_num'] =train['Date'].dt.week#.dt.date
test['Week_num'] =test['Date'].dt.week#.dt.date
train.head()

   gvkey  year                Filing    ...      Date_lag  Date_diff  Week_num
0   1004  2005  0001104659-05-033688    ...           NaT        NaN        29
1   1004  2006  0001104659-06-047248    ...    2005-07-22       -5.0        29
2   1004  2007  0001104659-07-055173    ...    2006-07-17        3.0        29
3   1004  2008  0001047469-08-008126    ...    2007-07-20       -8.0        28
4   1004  2009  0001047469-09-006783    ...    2008-07-11        5.0        29

[5 rows x 49 columns]